name: xmonad-config
version: "1.0"
synopsis: Alexey Zabelin's xmonad configuration
author: Alexey Zabelin
license: MIT
github: alexeyzab/dotfiles.git
dependencies:
- async
- base
- containers
- directory
- filepath
- http-client
- http-client-tls
- monad-loops
- process
- stm
- text
- time
- xmonad
- xmonad-contrib
- utf8-string
- taffybar
executables:
  custom-xmonad:
    main: xmonad.hs
    source-dirs: ./
    ghc-options:
    - -Wall
