resolver: lts-11.8
flags:
  xmonad-contrib:
    testing: false
    use_xft: false
  xmonad:
    testing: false
packages:
- .
- xmonad/
- xmonad-contrib/
extra-deps:
- X11-1.8
- ./taffybar
- dbus-1.0.1
- dbus-hslogger-0.1.0.1
- gi-gdk-3.0.16
- gi-gdkpixbuf-2.0.16
- gi-gdkx11-3.0.2
- gi-gtk-3.0.23
- gi-gtk-hs-0.3.6.1
- gi-pango-1.0.16
- ./taffybar/gtk-sni-tray
- gtk-strut-0.1.2.1
- rate-limit-1.4.0
- git: git@github.com:IvanMalison/status-notifier-item.git
  commit: 220610ac816d11aecfc8adcbb9ca240d9223e169
- time-units-1.0.0
- xml-helpers-1.0.0
- gi-dbusmenugtk3-0.4.2
- gi-gio-2.0.18
- gi-xlib-2.0.2
- spool-0.1
- gi-dbusmenu-0.4.1
