# This is the implicit global project's config file, which is only used when
# 'stack' is run outside of a real project.  Settings here do _not_ act as
# defaults for all projects.  To change stack's default settings, edit
# '/home/alexeyzab/.stack/config.yaml' instead.
#
# For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
packages: []
extra-deps:
  - dbus-1.0.1
  - dbus-hslogger-0.1.0.1
  - gi-gdk-3.0.16
  - gi-gdkpixbuf-2.0.16
  - gi-gdkx11-3.0.2
  - gi-gtk-3.0.23
  - gi-gtk-hs-0.3.6.1
  - gtk-sni-tray-0.1.3.1
  - gtk-strut-0.1.2.1
  - gtk3-0.14.9
  - rate-limit-1.4.0
  - status-notifier-item-0.2.2.0
  - time-units-1.0.0
  - xml-helpers-1.0.0
  - gi-dbusmenugtk3-0.4.1
  - gi-gio-2.0.18
  - gi-pango-1.0.16
  - gi-xlib-2.0.2
  - gio-0.13.5.0
  - spool-0.1
  - gi-dbusmenu-0.4.1
  - either-4.4.1.1
  - hackage-db-1.22
  - process-1.4.3.0
  - free-4.12.4
  - Cabal-2.0.1.1
allow-newer: true
resolver: lts-11.10
