#!/bin/sh

feh --bg-scale ~/wallpaper2.png

[[ -f ~/.config/Xresources ]] && xrdb ~/.config/Xresources
xset s off
xsetroot -cursor_name left_ptr
# urxvtd -q -f -o

# https://github.com/knopwob/dunst/issues/238
eval $(dbus-launch --sh-syntax --exit-with-session)

# activate natural scrolling
if [ -s ~/.Xmodmap ]; then
    xmodmap ~/.Xmodmap
fi

xmonad
