#!/bin/sh

feh --bg-scale ~/.local/share/wallpaper_new.jpg

[[ -f ~/.config/Xresources ]] && xrdb ~/.config/Xresources
xset s off
xsetroot -cursor_name left_ptr

# https://github.com/knopwob/dunst/issues/238
eval $(dbus-launch --sh-syntax --exit-with-session)

# activate natural scrolling
if [ -s ~/.Xmodmap ]; then
    xmodmap ~/.Xmodmap
fi

xmonad
