#!/bin/sh

# Make sure to add ~/.local/bin to the PATH because that is where `stack` is.
# We use `stack` to run `taffybar`.
export PATH="${HOME}/.local/bin:${PATH}"

# Source xmonad settings for xmonad and taffybar. This reads in the environment
# variables XMONAD_LOCAL_BIN_PATH and XMONAD_STACK_RESOLVER.
# XXX: This must be run using `.` and not `source` on systems where `sh` is
# not `bash`, because xinit always runs this file with `sh` (even if a
# different hashbang is specified).  Some versions of `sh` do know the
# `source` alias for `.`.
# . "${HOME}/.xmonad/xmonad_build_vars.sh"

# Needed for taffybar.
# xrandr --output HDMI-2 --off --output HDMI-1 --off --output DP-1 --off --output eDP-1 --primary --mode 1920x1080 -r 120 --pos 0x0 --rotate normal --output DP-2 --off
# xrandr --output HDMI-2 --primary --mode 2560x1440 -r 144 --pos 0x0 --rotate normal --output HDMI-1 --off --output DP-1 --off --output eDP-1 --off --output DP-2 --off
xrandr --output DVI-D-0 --off --output HDMI-0 --off --output DP-5 --off --output DP-4 --off --output DP-3 --off --output DP-2 --primary --mode 1920x1080 -r 144 --pos 0x376 --rotate normal --output DP-1 --off --output DP-0 --mode 1920x1080 -r 144 --pos 1920x0 --rotate left
status-notifier-watcher &

# Starting things up
gpg-agent --daemon &
nm-applet &
blueman-applet &
dropbox start &
pasystray &
dunst &
feh --bg-scale ~/.local/share/wallpaper.jpg &
xrdb ~/.Xresources
setxkbmap -option ctrl:nocaps
xset s off -dpms
xsetroot -cursor_name left_ptr

# Apps.
alacritty -e tmux &
emacs &
# XDG_CURRENT_DESKTOP=Unity google-chrome &
XDG_CURRENT_DESKTOP=Unity firefox &
# XDG_CURRENT_DESKTOP=Unity slack &
greenclip daemon &

# Start taffybar.
# PATH="${XMONAD_LOCAL_BIN_PATH}:$PATH" stack exec \
# 	--local-bin-path="${XMONAD_LOCAL_BIN_PATH}" \
# 	--resolver="${XMONAD_STACK_RESOLVER}" \
# 	-- taffybar &
stack exec /home/alexeyzab/.xmonad/local-bin/taffybar &

# Start xmonad.
# ${XMONAD_LOCAL_BIN_PATH}/xmonad &
stack exec ~/.xmonad/local-bin/custom-xmonad &
windowmanagerpid=$!
wait $windowmanagerpid
