# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/

# The following parameters are used by "stack new" to automatically fill fields
# in the cabal config. We recommend uncommenting them and filling them out if
# you intend to use 'stack new'.
# See https://docs.haskellstack.org/en/stable/yaml_configuration/#templates
templates:
  params:
    author-name: Alexey Zabelin
    author-email: hello@alexeyzabelin.com
    copyright: 2018 Alexey Zabelin
    github-username: alexeyzab

nix:
  enable: true
  pure: false
  path: [nixpkgs=/home/alexeyzab/nixpkgs]
  packages:
    - mysql57
    - openssl
    - pcre
    - pcre2
    - pcre2.dev
    - pcre2.out
    - oathToolkit
    - haskellPackages.alex
    - glpk
    - gcc
    - zlib.dev
    - zlib.out
    - pkgconfig
    - x11
    - xorg.libX11
    - xorg.libXext
    - xorg.libXinerama
    - xorg.libXrandr
    - xorg.libXrender
